# Generated by Django 2.0.13 on 2019-07-01 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=100)),
                ('bdesc', models.CharField(max_length=5000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cdesc', models.CharField(max_length=500)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_post', models.CharField(max_length=500)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=50)),
                ('rdesc', models.CharField(max_length=5000)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Cuisines')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=100)),
                ('rlocation', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=150)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Cuisines')),
            ],
        ),
        migrations.AddField(
            model_name='likedposts',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Recipes'),
        ),
        migrations.AddField(
            model_name='likedposts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Recipes'),
        ),
    ]
