# Generated by Django 2.0.13 on 2019-07-08 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 8, 17, 25, 56, 338990, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='ind',
            field=models.CharField(default='NA', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bdesc',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='rdesc',
            field=models.CharField(max_length=15000),
        ),
    ]
